### ISSUE TITLE
Suggestion: Add config option to hide world change message.

### ISSUE THREAD

**Issue by Aerodog** [bergerhealer/MyWorlds#11]
I would like to disable the 

`You have teleported to world 'world'!`

message for everyone (or specific groups, but not necessary).

Edit: Oh wait, can you just remove the message in Localization? I might just be dumb.

**Comment by bergerkiller** [comment]
You can set the message to empty, but I think itll still print that message to the players in that case. Its quite easy to add it so that empty messages to not get sent, though.

**Comment by Aerodog** [comment]
I never saw your reply! That change would be perfect.

**Comment by bbayu123** [comment]
Yes, just set the localization string to empty `''`
