### ISSUE TITLE
Teleporting between worlds makes your items invisible

### ISSUE THREAD

**Issue by sethwalker1** [bergerhealer/MyWorlds#15]
I created a group containing two worlds. Now, whenever I teleport from one world in the group to the other, my inventory is blank; However, if I click where an item was before the teleport, then my items all show up.

**Comment by MelonLord145** [comment]
Should be fixed in https://github.com/MelonLord145/MyWorlds

**Comment by bergerkiller** [comment]
I worked this out with somebody on Discord, so I'm fairly sure this is fixed now.
