### ISSUE TITLE
Users are unable to interact with some blocks

### ISSUE THREAD

**Issue by clmcdonald** [bergerhealer/MyWorlds#19]
After installing this plugin, some users were unable to open certain chests and press buttons. They were able to open some chests but not others, and it is not clear why they are able to open some but not others. In some places they could not place down blocks either. Once again, it wasn't global. In some places they were able to place blocks, in other places they could not.

At first I thought it was just a permissions issue, but I tried giving the users these two permissions and it did not solve the problem: `myworlds.world.build.*`, `myworlds.world.use.*`

Any idea why this is happening?

I am on 1.16 using MyWorlds version 1.16.1-v1

**Comment by bbayu123** [comment]
Closing issue, stale, more information is needed.

If you are still following this issue, please tell is what permission manager you are using. A certain one has a verbose command to see what permission is being checked when you try to interact with the world.
