### ISSUE TITLE
Custom World generation by Player

### ISSUE THREAD

**Issue by ErythroCraft** [bergerhealer/MyWorlds#23]
Hi

I'm using you're plugin and love it.

Have you got an example to give player permission to create there own world?

My idea is, to give any player rights to create there own world like /world create %player_name%
I know that is not simple, but I think it's new.

Well, the user/player only must type the command and have rights for the world only.

Is this feasible?

And sorry my englisch ist not the best. I'm German.

**Comment by Andre601** [comment]
I on my part don't think this would be a good idea as people could just spam the command to mass-create worlds and use up storage and ram.

At most should a separate plugin handle this and trigger a world creation with MyWorlds once certain requirements are met.
But then again: Allowing each player to have their own world wouldn't go well at the end as each world would take up large amounts of storage unelss you would use a different storage format like SlimeRasterFormat (SRF) available in (Advanced)SlimeWorldManager.

**Comment by ErythroCraft** [comment]
I thought so too. But it would be feasible to regulate the whole thing via permissions and the configuration file. So that the player with the corresponding pemissions can only create a certain number of worlds.

For example, I thought that the player with the permission myworld.user.command.create could execute the command / mw create. Then a world is created which is called "worldName. {PlayerName}" like the player name.
The player automatically becomes the owner and has the permission myworld.user.world for his world and only when he is in the world.

Not everyone should be allowed to do that either. I was just thinking of a future for YouTubers and streamers.

But of course it's your decision whether you want to incorporate such a future.

**Comment by ErythroCraft** [comment]
I thought so too. But it would be feasible to regulate the whole thing via permissions and the configuration file. So that the player with the corresponding pemissions can only create a certain number of worlds.

For example, I thought that the player with the permission myworld.user.command.create could execute the command / mw create. Then a world is created which is called "worldName. {PlayerName}" like the player name.
The player automatically becomes the owner and has the permission myworld.user.world for his world and only when he is in the world.

Not everyone should be allowed to do that either. I was just thinking of a future for YouTubers and streamers.

But of course it's your decision whether you want to incorporate such a future.
