### ISSUE TITLE
Issue running on paper

### ISSUE THREAD

**Issue by y23bv0** [bergerhealer/MyWorlds#25]
when trying to run the plugin on a paper spigot server, it simply says "Could not load 'plugins\MyWorlds-1.16.5-v1.jar' in folder 'plugins' " when starting the server

**Comment by Andre601** [comment]
What is the full error? This can't be everything.

Also, make sure BKCommonLib is installed as MyWorlds depends on it, as mentioned heavily on the Spigot page.

**Comment by y23bv0** [comment]
i don't know how i didn't see that, but thank you! it works now!

**Comment by Andre601** [comment]
If that is fixed, should you close the issue.
