### ISSUE TITLE
Disabling bed respawn on a different world disables it for all worlds

### ISSUE THREAD

**Issue by breadbyte** [bergerhealer/MyWorlds#31]
Steps to reproduce:

From an empty server:
1. Create a hub world. `/world create hub`
2. Set the following configuration options for the `world` world (main world):
- `/world respawn bed enable`
3. Set the following configuration options for the `hub` world:
- `/world respawn bed disable`
4. Set a bed in `world` as your respawn point.
5. Teleport to the hub. `/tpp hub`
6. Teleport back to the main world. `/tpp world`
7. Execute `/kill`.
8. Expected a respawn back to the bed, but instead is respawned on the world spawn.

(Additionally, I noticed that `/world respawn info` does not contain information for bed spawns, it defaults to `set to the current World spawn` instead.)

The `world -> hub -> world` teleport is crucial for the plugin to 'forget' the respawn rules and the bed for the current world.
Otherwise, it works normally without teleporting to the hub world.

I might be doing something wrong with my configuration, but my goal here is simply to disable bed spawns in the hub and enable it in the main world (as I'm writing this, i realize this is kind of redundant in our production server as the hub is protected from block manipulation anyways, so no beds can get there in the first place, but I digress.)

**Comment by bergerkiller** [comment]
So I committed this fix a while back but forgot to update this issue ticket https://github.com/bergerhealer/MyWorlds/commit/364fd33be5b64d221cc9d76d7ffd899acf7bd2ee

Can you check if this problem is now resolved? Performing the steps you outlined no longer reproduce the problem for me.

**Comment by breadbyte** [comment]
Can confirm that the issue is now resolved. Thank you!
