### ISSUE TITLE
Please help me!

### ISSUE THREAD

**Issue by soypeto** [bergerhealer/MyWorlds#36]
I could add the type process when they change world that does not send you to the location set in the world world or world_the_end or world_nether because it happens many times that the user is in the world of world_the_end and when he leaves and enters there is no command that says that it was last in the world_the_end and it will place it in the last location of said world, if not it automatically sends it to the world because the /tpp command is here, I don't know if it makes you understand that it is :D

**Comment by bergerkiller** [comment]
> I could add the type process 
What does this mean? World type? Game mode type?

> and when he leaves and enters 
From the server or to another world?

What exactly is this about? Do you want players to join a fixed spawn point or lobby when they join the server? Do you want players that use /tpp to teleport to the world spawn, or to their last position?

Maybe this is relevant: https://wiki.traincarts.net/p/MyWorlds/Commands#Teleport_to_the_last_position_on_a_group_of_worlds
