### ISSUE TITLE
Failed to update class loader registry

### ISSUE THREAD

**Issue by FunkyNico** [bergerhealer/MyWorlds#38]
Hello, since paper add preloader system now the plugin doesn't startup correctly. 

Log: https://pastebin.ubuntu.com/p/yqPzKsk6K7/

Server: Purpur version git-Purpur-1920 (MC: 1.19.3) (Implementing API version 1.19.3-R0.1-SNAPSHOT) (Git: 1d7602d on HEAD).

Thanks.

**Comment by bbayu123** [comment]
Update BKCommonLib and MyWorlds please.

**Comment by FunkyNico** [comment]
> 

I'm stupid. Thanks.
