### ISSUE TITLE
Nether portal dont break

### ISSUE THREAD

**Issue by SkyWaves123** [bergerhealer/MyWorlds#39]
Upon players breaking the nether portal's frame, the portal remains intact. https://imgur.com/54TCFcK
I didnt know what plugin caused this but when i removed MyWorlds , the portal broke and the bug dissapeared.

**Comment by bergerkiller** [comment]
There's a config.yml option to turn this off (overridePortalPhysics: false)

**Comment by SkyWaves123** [comment]
this fixed my issue. tnx

**Comment by aml2023529** [comment]
WIKI配置世界权限没了

**Comment by bbayu123** [comment]
Closing issue, not a bug, workaround suggested.
