### ISSUE TITLE
MyWorlds Placeholders Not Referencing Specified World 

### ISSUE THREAD

**Issue by Virkis** [bergerhealer/MyWorlds#44]
MyWorlds-1.20.1-v1-236

Papi 2.11.3

Using `%myworlds_world_time[otherworldhere]%` doesn't reference the world that's within the brackets, and instead references the world the user of the placeholder is in as if they had used `%myworlds_world_time%` instead. 
This seems to be the same behavior for all other instances of MyWorld's placeholders when using `[otherworldhere]`.

One can throw in anything within the `[]` and it provides no errors and simply returns the current world that the player is in.

Console throws no errors.

According to [the Myworld wiki,](https://wiki.traincarts.net/p/MyWorlds/PAPI) it should be parsing properly.

**Comment by doppelganger237** [comment]
I also encountered this situation, and after reading its [source code](https://github.com/bergerhealer/MyWorlds/blob/master/src/main/java/com/bergerkiller/bukkit/mw/papi/MyWorldsPAPIHandlerImpl.java#L79-L88), I find a solution.

![image](https://github.com/bergerhealer/MyWorlds/assets/30953850/d42d989a-af28-4917-9799-03cede99b2d0)

change openerIdx to openerIdx+1 in line 82 .

**Comment by bergerkiller** [comment]
> I also encountered this situation, and after reading its [source code](https://github.com/bergerhealer/MyWorlds/blob/master/src/main/java/com/bergerkiller/bukkit/mw/papi/MyWorldsPAPIHandlerImpl.java#L79-L88), I find a solution.
> 
> ![image](https://user-images.githubusercontent.com/30953850/249690923-d42d989a-af28-4917-9799-03cede99b2d0.png)
> 
> change openerIdx to openerIdx+1 in line 82 .

Thanks, that does look like it is the problem so Ive changed it. Does this work now? https://ci.mg-dev.eu/job/MyWorlds/237/

**Comment by Virkis** [comment]
Hey thanks for the quick turnaround and fix to the both of you! Can confirm it works as intended with build 237.

**Comment by bbayu123** [comment]
Closing as resolved.
