### ISSUE TITLE
Error with SuperiorSkyblock2

### ISSUE THREAD

**Issue by YKDZ** [bergerhealer/MyWorlds#45]
https://mcpaste.com/0fe686b11ddb1e0e3654191bce5ee6c3
The error appears every time the server is restarted, followed by the server shutting down automatically after the startup completes. The problem is fixed after bringing the server up again, after which the process is repeated.

My platform is git-Purpur-2005 (MC: 1.20.1)*
Plugin version is MyWorlds 1.20.1-v1 and SuperiorSkyblock2-2023.2-b40

**Comment by bbayu123** [comment]
Not a MyWorlds issue. Report this to your chunk generator.
