### ISSUE TITLE
World change messages

### ISSUE THREAD

**Issue by Echo69420** [bergerhealer/MyWorlds#46]
Sorry if I'm being ignorant, but I can't think of any other way this would be changed. So if it's not already possible, PLEASE add an option in the config that allows you to turn of world change messages. Because even when you're not op, it always says when and what world you've been teleported to. Please fix. Thank you in advance.

**Comment by bbayu123** [comment]
Canned response from our Discord server:
> To disable the My Worlds messages displayed when players teleport, edit `plugins/My_Worlds/Localization.yml` and set the message to hide to `''` (two single quotes)
