### ISSUE TITLE
Trades clearing everytime you edit them

### ISSUE THREAD

**Issue by NekaouMike** [bergerhealer/MyWorlds#52]
I placed down a shopkeeper NPC and sneek+right clicked to edit trade. Then when just right clicking they show up as normal. Then one you shift+right click again all the trades get lost and when you exit it saves with no trades if none where inputted.

This is on 1.20.2

**Comment by bergerkiller** [comment]
Wrong project?

**Comment by NekaouMike** [comment]
Oh crap yeahh
