### ISSUE TITLE
Please update the Maven repo

### ISSUE THREAD

**Issue by Kiritorz** [bergerhealer/MyWorlds#53]
From the [Wiki](https://wiki.traincarts.net/p/MyWorlds) I didn't see any API pages but i found the [MyWorlds-MavenRepo](https://mvnrepository.com/artifact/com.bergerkiller.bukkit/MyWorlds) which only have version 1.15.2-v1 at Jun 30, 2020.
I'm appreciate if you can update the Maven repo to LATEST version so that I can fix the Multiverse dependencies injected to MyWorlds in my own plugins. Thanks!

**Comment by 56738** [comment]
It's in the BKCommonLib repository: https://github.com/bergerhealer/BKCommonLib#dependency-information

**Comment by Kiritorz** [comment]
Found it! Thanks 😄 !
