### ISSUE TITLE
Treat the dimensions as one world

### ISSUE THREAD

**Issue by chelminski** [bergerhealer/MyWorlds#59]
Hi ;)
Add an option to treat identical world names but in different dimensions as one world. What I mean? On my server, each user can create their own set of worlds and invite their friends to it.  It looks like this:
- chelminski
- chelminski_nether
- chelminski_the_end

**Having the following configurations set:**
`useWorldInventories: true`

Expectations: Players within a world can have the same eq (e.g. chelminski, chelminski_nether, chelminski_the_end). But going beyond (e.g. into the vilus world, vilus_nether, vilus_the_end) they must have a different set of eqs.

Reality: The player has a different eq in the chelminski_nether world and a different eq in the chelminski_the_end world.

Along these lines, I would also like to ask you to add:
- Chat per set of worlds (This way with no need to type every world name in config, just auto-detect)
- TAB per set of worlds

I think introducing these options would be very helpful. The option can be split:
`useWorldInventories: true/false`
`InventoriesWorldsKit: true/false` 
etc.

**Comment by bergerkiller** [comment]
have you tried `/mw inventory merge chelminski chelminski_nether chelminski_the_end` ?

Normally you would do `/mw inventory first_time_activation` or some such and it will automatically set up a merged inventory for all worlds. Toggling the config option does not do that.

**Comment by chelminski** [comment]
I will try to automate this command somehow, but it would be nice if I had a placeholder that tells whether a given world has connected inventories. E.g.
`%mw_inventory_merged_chelminski%` the return value would be `yes/no`

Then my problem would be solved, I can write a script executed when a user joins the server (in my case, the world name is a variable, each user is assigned a world to which he connects as the default).
`if %mw_inventory_merged_<chelminski>%=yes run /mw inventory merge chelminski chelminski_nether chelminski_the_end`

Alternatively, tell me how else I can do it because I have no idea at the moment. 🙈🙈
