### ISSUE TITLE
Command queue

### ISSUE THREAD

**Issue by chelminski** [bergerhealer/MyWorlds#60]
Hi ;)
I have a little problem with generating a large number of worlds. The problem is that when several worlds are generated, they are not generated sequentially, but all at the same time. This gives me java errors and uses a lot of resources. Would it be possible for the world creation action to be queued? Creating one world and once that world is created creates the next one. Or possibly set the maximum number of threads in the config. Currently, when many users start generating worlds at the same time, the server restarts. 

Commands to generate 45 worlds, of which only 5 were generated correctly and the server stopped :/ .

`[14:49:21] [Spigot Watchdog Thread/ERROR]: The server has stopped responding! This is (probably) not a Spigot bug.`
`[14:49:21] [Spigot Watchdog Thread/ERROR]: If you see a plugin in the Server thread dump below, then please report it to that author`
`[14:49:21] [Spigot Watchdog Thread/ERROR]: 	 *Especially* if it looks like HTTP or MySQL operations are occurring`
`[14:49:21] [Spigot Watchdog Thread/ERROR]: If you see a world save or edit, then it means you did far more than your server can handle at once`
`[14:49:21] [Spigot Watchdog Thread/ERROR]: 	 If this is the case, consider increasing timeout-time in spigot.yml but note that this will replace the crash with LARGE lag spikes`
`[14:49:21] [Spigot Watchdog Thread/ERROR]: If you are unsure or still think this is a Spigot bug, please report to https://www.spigotmc.org/`
`[14:49:21] [Spigot Watchdog Thread/ERROR]: Be sure to include ALL relevant console errors and Minecraft crash reports`
`[14:49:21] [Spigot Watchdog Thread/ERROR]: Spigot version: 3950-Spigot-2888990-d485cde (MC: 1.20.2)
`
Would you be able to help me and create a queue for the create command in the plugin?

**Comment by bergerkiller** [comment]
Unfortunately its largely out of my control. Bukkit does world loading/generating, and the create command does a bunch of chunk generating synchronously despite my attempt at preventing it. This causes the server to stall.

It might help to create a 'template' world and doing /mw copy + /mw load instead, so it doesnt have to regenerate spawn every time.

**Comment by chelminski** [comment]
/mw copy + /mw load, doesn't seem like a good option to me, each world should be a little different in this case. 

I'm looking for a plugin that could do something about this, but I see that everything is abandoned and mostly has a different effect. I also have no knowledge of Java/plugin programming 😭😭
I've seen something like this, but it's completely redundant. I don't know what I can actually do, currently my server cannot work in this state :/
https://github.com/bjorno43/DelayedCommand

Any ideas on how to handle this?

**Comment by chelminski** [comment]
Ok. Solved
https://www.spigotmc.org/resources/command-timer.24141/
