### ISSUE TITLE
Bypass gamemode for admins

### ISSUE THREAD

**Issue by Vlader97** [bergerhealer/MyWorlds#61]
I'm trying to set that admins don't switch gamemode when changing world, but I can't get it to work.
Could you help me?

**Comment by bergerkiller** [comment]
Make sure config.yml `forceGamemodeChanges` is set to false (not true)

Then you can grant admins the myworlds.world.ignoregamemode permission to not have game mode changes affect them

**Comment by Vlader97** [comment]
Thank you for a quick response.
It works now. :)
