### ISSUE TITLE
KeepInventory Gamerule Per World

### ISSUE THREAD

**Issue by GreyLake** [bergerhealer/MyWorlds#66]
Hi, Sorry if this has already been answered, I'm trying to migrate away from multiverse, and I was wondering if there was a way to set per world "keep-inventory" (in one world the player can lose their items, but in another world they can't lose their items, assuming that their inventories are merged between worlds), it's a little bit weird of a Scenario. Hope you can send me in the right direction, thanks!

**Comment by bergerkiller** [comment]
I think game rules on bukkit are already per world (applied to the world youre inside of). But I could be wrong. Can you check?

**Comment by GreyLake** [comment]
Thank you! Sorry for the trouble lol, probably should have checked that haha
