### ISSUE TITLE
Can command aliases "world" removed ? : /world command name conflict with essentialsx

### ISSUE THREAD

**Issue by RadND** [bergerhealer/MyWorlds#69]
ess has a /world command too, when use, it tp player. very handy, but by now due to name conflict i have to set false permission of /ess:world for my player, force them to use /world rejoin <world_name>

can the code in myworlds be changed to register command in a different name? like /mw <create|rejoin|...> .
i can do a pr if your say yes but dont have time, just pure string replace after all.

**Comment by bergerkiller** [comment]
But /mw alias should already exist

**Comment by RadND** [comment]
> But /mw alias should already exist

sorry,now it should looks meaningful

**Comment by RadND** [comment]
@bergerkiller   rename "world" to "worlds" solve my problem,too. And I thought it would make more sense. 
Player can teleport to a "world" , and then manage "worlds".

**Comment by RadND** [comment]
@bergerkiller  rename "world" to "worlds" solve my problem,too. And I thought it would make more sense. 
Player can teleport to a "world" , and then manage "worlds".

**Comment by bergerkiller** [comment]
Well I cant really go change that and get rid of /world as it would break it for people. In general I recommend people stick with /mw to avoid ess-ex conflicts

**Comment by RadND** [comment]
to people who came here, luckily in this paricular case , a (not) perfect solution easier(?) than fork and compile plugin do exists

you can disable or rename /world by modify plugin.yml,which remain the same after compile,
so you can 
- unzip the jar file 
- modify plugin.yml ,rename every node contain world to worlds
-  zip it back (without compress) 

after this tab complete will still confronting, however thx/due to how myworlds tab complete is written by now,when taping "\world ",only essx 's tab completing will responding 

problem sovled , BUT
- myworlds "short" command (gen diff i ...) completion got messd up
- when update ,you need do again.

hope this helps
