### ISSUE TITLE
Warn in console

### ISSUE THREAD

**Issue by Acetaminofenuwu** [bergerhealer/MyWorlds#71]
Excuse me good day, I'm having a problem in the console, this is the log:

Log: https://mclo.gs/6sgepoY

 That warn is spamming me a lot in the console and it's horrible.

Below I explain what I did before that happened.

Everything was normal
I had put in the custom biomes plugin
For this I need to use the myworlds plugin instead of multiverse core because the biomes plugin is only compatible with myworld

So I created the custom world with the command that comes with IRIS (custom biomes plugin) with the name “temp2” and then in server.properties I put the custom world as the main world which in this case is called temp2

Then I changed the names of the nether and ender worlds at the beginning with “temp2_nether” “temp2_the_end” because that is what the custom biomes plugin we made said.

And I opened the server and everything was fine. I went to see everything and the previous worlds created with multiverse core had now been moved to myworld and I could go to them.

But I didn't like the way the custom biome world "temp2" looked and I wanted to change the biome, so what I did was go to server properties and delete "temp2" as the main world and put "world"
I deleted the custom biome plugin along with its folder and deleted the worlds that had the name "temp2" from the nether and ender survival. Then I turned off the server and turned it back on and then turned it off and put the IRIS aphid back in so that everything would form again and do the whole procedure again.

And everything was fine, I created the world and the same biome appeared again, then I started to investigate how to change it but it was too late. In the console it was throwing that error. I don't know what got misconfigured 😭.
And now I don't want to touch the server because I feel that what I do can be lost and it scares me.

But what I want you to know is that the spam didn't tell me that there were bad chunks like temp2.

It told me that the incomplete chunks were from these worlds:
boxpvp: a flat world that I created with a flat multiverse core and with only one building. It's a box pvp structure.
And 2 worlds that I downloaded with the elite mobs plugin that I created using the command that they say to create a world similar to the iris method to create worlds with the plugin itself.

Please help me to solve. 🙏

**Comment by Acetaminofenuwu** [comment]
The full log: https://mclo.gs/5tTW6GD

**Comment by bergerkiller** [comment]
Looks like a server issue to me, and you maked it as closed so I guess you found a fix for these warnings? Not something from myworlds anyways.

**Comment by Acetaminofenuwu** [comment]
> Looks like a server issue to me, and you maked it as closed so I guess you found a fix for these warnings? Not something from myworlds anyways.

Yes, It was error of Iris Plugin. Thanks.
